- hosts: controller
  remote_user: root
  tasks:
  - name: configure IP
    shell: netplan apply
  - name: set hostname
    shell: hostnamectl set-hostname controller

- hosts: network
  remote_user: root
  tasks:
  - name: configure IP
    shell: netplan apply
  - name: set hostname
    shell: hostnamectl set-hostname network

- hosts: compute1
  remote_user: root
  tasks:
  - name: configure IP
    shell: netplan apply
  - name: set hostname
    shell: hostnamectl set-hostname compute1

